# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webTitle', models.CharField(max_length=30, verbose_name='网页title')),
                ('webUrl', models.CharField(max_length=30, verbose_name='网址')),
                ('webDetail', models.CharField(max_length=500, verbose_name='网页内容')),
                ('webAuthor', models.CharField(max_length=30, verbose_name='作者')),
                ('webCreateTime', models.DateField(verbose_name='生成时间')),
                ('webAmendTime', models.DateField(verbose_name='修改时间')),
                ('webAmender', models.CharField(max_length=30, verbose_name='修改人')),
                ('FirstReviewer', models.CharField(max_length=30, verbose_name='第一审核人')),
                ('FirstInstanceTime', models.DateField(verbose_name='一审时间')),
                ('FirstInstanceOpinion', models.CharField(max_length=30, verbose_name='一审意见')),
                ('FirstInstanceStatus', models.CharField(max_length=30, verbose_name='一审状态')),
                ('SecondReviewer', models.CharField(max_length=30, verbose_name='第二审核人')),
                ('SecondInstanceTime', models.DateField(verbose_name='二审时间')),
                ('SecondInstanceOpinion', models.CharField(max_length=30, verbose_name='二审意见')),
                ('SecondInstanceStatus', models.CharField(max_length=30, verbose_name='二审状态')),
                ('Approver', models.CharField(max_length=30, verbose_name='批准人')),
                ('ApprovalTime', models.DateField(verbose_name='批准时间')),
                ('ApprovalOpinion', models.CharField(max_length=30, verbose_name='批准意见')),
                ('APPROVALStatus', models.CharField(max_length=30, verbose_name='批准状态')),
            ],
            options={
                'verbose_name': '网页信息',
                'verbose_name_plural': '网页信息',
            },
        ),
    ]
