# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': '缴费记录', 'verbose_name_plural': '缴费记录'},
        ),
        migrations.AddField(
            model_name='user',
            name='passwordf',
            field=models.CharField(default='********', editable=False, max_length=8, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='internetrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='internetrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
