# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170826_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordf',
            field=models.CharField(default='********', max_length=8, verbose_name='密码'),
        ),
    ]
