# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170902_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetrecord',
            options={'verbose_name': '上网记录', 'verbose_name_plural': '上网记录'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
