# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170903_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwordf',
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='是否是作者'),
        ),
    ]
