# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170903_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=6, null=True, verbose_name='性别'),
        ),
    ]
