# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0005_auto_20170905_0837'),
        ('users', '0018_auto_20170903_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentName', models.CharField(max_length=30, verbose_name='评论人')),
                ('commentTime', models.DateTimeField(null=True, verbose_name='评论时间')),
                ('commentLevel', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='评分')),
                ('commentReviewer', models.CharField(max_length=30, verbose_name='审核人')),
                ('commentReviewTime', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('reviewStatus', models.CharField(choices=[('0', '未审核'), ('1', '正在审核'), ('2', '已审核'), ('3', '批准'), ('4', '拒绝')], max_length=1, null=True, verbose_name='审核状态')),
                ('web', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artical.web')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
