# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.School'),
        ),
    ]
